### ISSUE TITLE
(｡･∀･)ﾉﾞ嗨嗨~咱有个问题~~~

### ISSUE THREAD

**Issue by hatsuyuki280** [sulf1ron/u2#1]
这是啥~~~
好像是telegrame的bot。。。
但是好像还看到了live2d的样子~~~

感觉好厉害quq
---by鱼唇的初雪

**Comment by hatsuyuki280** [comment]
欸？？？
好像没找到撤回问题的按钮欸quq
还说要不要直接撤销了去Telegram上直接问呢quq

**Comment by sulf1ron** [comment]
关于幼兔娘所有的代码都先暂存这里了
有 tg-bot 和 status 站的源码
